name: my-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.20
  - pip=24.3.1
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - ld_impl_linux-64=2.43
  - libffi=3.4.6
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgomp=14.2.0
  - liblzma=5.6.4
  - liblzma-devel=5.6.4
  - libnsl=2.0.1
  - libsqlite=3.49.1
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.4.1
  - readline=8.2
  - setuptools=75.3.0
  - tk=8.6.13
  - wheel=0.45.1
  - xz=5.6.4
  - xz-gpl-tools=5.6.4
  - xz-tools=5.6.4
  - pip:
      - awkward==2.6.10
      - awkward-cpp==40
      - cramjam==2.9.1
      - fsspec==2025.2.0
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - joblib==1.4.2
      - numpy==1.24.4
      - packaging==24.2
      - pillow==10.4.0
      - pot==0.9.5
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - threadpoolctl==3.5.0
      - torch==1.7.1+cu110
      - torchaudio==0.7.2
      - torchvision==0.8.2+cu110
      - tqdm==4.67.1
      - typing-extensions==4.12.2
      - uproot==5.4.2
      - vector==1.6.1
      - xxhash==3.5.0
      - zipp==3.20.2
